### ISSUE TITLE
Can't run project `undefined method delete_suffix`

### ISSUE THREAD

**Issue by flachica** [open-sdg/open-sdg-simple-starter#17]
I do a clone and follow the instructions to start the project locally and it returns "Liquid Exception: undefined method` delete_suffix 'for "10,": String in /_layouts/post.html "

It seems to be the date treatment. If I run jekyll serve -t from dual instance repository it returns "/var/lib/gems/2.4.0/gems/jekyll-open-sdg-plugins-1.0.0/lib/jekyll-open-sdg-plugins/ translate_date.rb: 48 "

My machine has the configuration es_ES

**Comment by flachica** [comment]
Full log: `bundle exec jekyll build --config=config_site.yml --verbose --trace'

Logging at level: debug
Configuration file: config_site.yml
         Requiring: jekyll-remote-theme
         Requiring: jekyll-open-sdg-plugins
            Source: www
       Destination: /home/flachica/proyectos/open-sdg-simple-starter/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Theme: open-sdg/open-sdg@master
      Theme source: /tmp/jekyll-remote-theme-20200829-8788-2h580g
Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
      Remote Theme: Downloading https://codeload.github.com/open-sdg/open-sdg/zip/master to /tmp/jekyll-remote-theme-20200829-8788-s9htx.zip
      Remote Theme: Unzipping /tmp/jekyll-remote-theme-20200829-8788-s9htx.zip to /tmp/jekyll-remote-theme-20200829-8788-2h580g
         Requiring: jekyll-open-sdg-plugins
           Reading: _posts/2020-01-10-test-post-1-en.md
           Reading: _pages/faq.md
           Reading: _pages/categories.md
           Reading: _pages/contact.md
           Reading: _pages/news.md
           Reading: _pages/about.md
           Reading: _pages/cookies.md
           Reading: _pages/guidance.md
             Theme: Ignoring /assets/img/SDG_logo.png in theme due to existing file with that path in site.
             Theme: Ignoring /assets/img/favicons/favicon-114.png in theme due to existing file with that path in site.
             Theme: Ignoring /assets/img/favicons/favicon-57.png in theme due to existing file with that path in site.
             Theme: Ignoring /assets/img/favicons/favicon-72.png in theme due to existing file with that path in site.
             Theme: Ignoring /assets/img/favicons/favicon.ico in theme due to existing file with that path in site.
             Theme: Ignoring /assets/img/favicons/favicon.png in theme due to existing file with that path in site.
        Generating: JekyllOpenSdgPlugins::FetchRemoteData finished in 0.016295352 seconds.
        Generating: JekyllOpenSdgPlugins::CreateIndicators finished in 0.002458232 seconds.
        Generating: JekyllOpenSdgPlugins::CreateGoals finished in 0.000987066 seconds.
        Generating: JekyllOpenSdgPlugins::CreatePages finished in 5.4163e-05 seconds.
        Generating: JekyllOpenSdgPlugins::SDGVariables finished in 0.065271037 seconds.
        Generating: JekyllOpenSdgPlugins::SearchIndex finished in 0.113107152 seconds.
         Rendering: _posts/2020-01-10-test-post-1-en.md
  Pre-Render Hooks: _posts/2020-01-10-test-post-1-en.md
  Rendering Markup: _posts/2020-01-10-test-post-1-en.md
  Rendering Layout: _posts/2020-01-10-test-post-1-en.md
     Layout source: theme
  Liquid Exception: undefined method `delete_suffix' for "10,":String in /_layouts/post.html
      Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20200829-8788-2h580g
/var/lib/gems/2.4.0/gems/jekyll-open-sdg-plugins-1.0.0.rc23/lib/jekyll-open-sdg-plugins/translate_date.rb:48:in `block in t_date': undefined method `delete_suffix' for "10,":String (NoMethodError)
	from /var/lib/gems/2.4.0/gems/jekyll-open-sdg-plugins-1.0.0.rc23/lib/jekyll-open-sdg-plugins/translate_date.rb:44:in `each'
	from /var/lib/gems/2.4.0/gems/jekyll-open-sdg-plugins-1.0.0.rc23/lib/jekyll-open-sdg-plugins/translate_date.rb:44:in `t_date'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /var/lib/gems/2.4.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:126:in `render_liquid'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:195:in `render_layout'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:88:in `render_document'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:62:in `run'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:479:in `render_regenerated'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:463:in `each'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:463:in `block in render_docs'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:462:in `each_value'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:462:in `render_docs'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:191:in `render'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:71:in `process'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/command.rb:28:in `process_site'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:65:in `build'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:36:in `process'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.4.0/gems/jekyll-3.8.4/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

**Comment by flachica** [comment]
Oh, sorry, I was not updated with last version of ruby. I find this. The method delete_sufix was introduced in 2.5.5 version.
